### ISSUE TITLE
World name has changed in 1.4.1 BSkyBlock_world to BSkyBlock-world

### ISSUE THREAD

**Issue by krustymk** [BentoBoxWorld/BSkyBlock#107]
**Description**
World name has changed in 1.4.1 BSkyBlock_world to BSkyBlock-world

**Steps to reproduce the behavior:**
update to 1.4.1 and restart server

**Expected behavior**
I expect to not have new worlds generated 

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by tastybento** [comment]
Thanks. Actually, the code around this hasn't changed for 9 months and it was actually a mismatch between the world name in the default config.yml and the internal Settings class. During your update, it must have used the Settings class name, maybe because the config.yml wasn't there or something. Anyway, it's fixed now so thanks.
