### ISSUE TITLE
Island radius

### ISSUE THREAD

**Issue by Joeripoes** [BentoBoxWorld/BSkyBlock#113]
My island distance is set like this:  distance-between-islands: 100.
I expected the first island to be at 0 100 0, this is correct. But the second island was placed at 0 100 224 and not 0 100 200 as I expected. Why is that and can I fix that?

**Comment by BONNe** [comment]
In 1.4 version BentoBox works with whole chunks. So all island distances are rounded till closest chunk border, and you cannot change it.
It could change in 1.5 version, but could you explain why would you need island centers in 200?

Chunk borders are more convenient island border as it allows to utilize whole island.
F.e. if a slime chunk is at the island border and you have split chunk in half, then player could not use that slime chunk, because some part of it is in other player island.

**Comment by Joeripoes** [comment]
Ah thats true, I just thought the coords look cleaner, thanks

**Comment by BONNe** [comment]
As I understand from 1.5 changes, it will be able to set "nicer" coords again in next release.
But as a skyblock player, I do not recommend to do it.

**Comment by tastybento** [comment]
@Joeripoes What version of BentoBox and BSkyBlock were/are you using?
