### ISSUE TITLE
Island team size bug

### ISSUE THREAD

**Issue by cloakfox** [BentoBoxWorld/BSkyBlock#181]
So I was trying to give my players with the "[Member]" rank some extra team member slots through permissions. I'd give them this permission `bskyblock.team.maxsize.20' and it wouldn't work. The max team members would stay on 4.

So I checked the config file and saw that you need to up it. So I raised it to 20 and gave the permission bskyblock.team.maxsize.20 to my members, whilst giving my default players bskyblock.team.maxsize.4.

The whole server was however able to invite 20 team members, regardless of permissions I had setup.

PaperSpigot 1.13.2
bskyblock build: 424

**Comment by tastybento** [comment]
It's not possible to set permissions to be lower than the config value, so that approach will not work.
I cannot replicate the issue of settings permissions for players. When I set bskyblock.team.maxsize.20 and the player does /is team, they see they can invite up to 19 more players. So, I think this is a permission setting issue. What permission plugin are you using and how do you set the permissions?

**Comment by cloakfox** [comment]
Yeah so if I set the config option to 4 and give donators the permission bskyblock.team.maxsize.20 with LuckPerms they can still only invite 3 team members instead of 19.

**Comment by cloakfox** [comment]
After more testing it seems to be working now, now I swear I wasn't doing anything wrong with permissions but yeah it seems to be fixed right now.

No idea what caused this, but after this mornings auto reboot everything worked. Perhaps bskyblock doesn't take reloads very well. Idk.

**Comment by tastybento** [comment]
Okay, weird. Closing for now.
