### ISSUE TITLE
Server stops responding when creating an island

### ISSUE THREAD

**Issue by vojta478** [BentoBoxWorld/BSkyBlock#231]
#### Describe the bug

The server stops responding when creating or resetting island.

#### Steps to reproduce the behavior

Upgrade ASkyBlock (MC 1.12.2) to BentoBox (MC 1.15) using the Converter addon for BentoBox.
Start the server and create or reset island.

#### Expected behavior

Create new island without errors.

#### Screenshots and videos (Optional)

![Screenshot (9)](https://user-images.githubusercontent.com/12088751/71314924-58906e00-2452-11ea-9816-3aff6de4d6d1.png)
![Screenshot (10)](https://user-images.githubusercontent.com/12088751/71314929-62b26c80-2452-11ea-8933-7a780bf4bb79.png)
![Screenshot (11)](https://user-images.githubusercontent.com/12088751/71314930-6a721100-2452-11ea-9a45-6eef0125a882.png)

##### BentoBox Version (Mandatory)

```
[00:24:00 INFO]: Running PAPER 1.15.
[00:24:00 INFO]: BentoBox version: 1.9.2
[00:24:00 INFO]: Database: JSON
[00:24:00 INFO]: Loaded Game Worlds:
[00:24:00 INFO]: ASkyBlock (BSkyBlock): Overworld, Nether, End
[00:24:00 INFO]: Loaded Addons:
[00:24:00 INFO]: Biomes 1.6.0.1 (ENABLED)
[00:24:00 INFO]: BSkyBlock 1.9.0 (ENABLED)
[00:24:00 INFO]: Challenges 0.8.0 (ENABLED)
[00:24:00 INFO]: Warps 1.9.0 (ENABLED)
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

I have tried disabling every other plugin and it doesn't work either.

**Comment by Poslovitch** [comment]
Have you progressively updated your world from 1.12 to 1.13, then to 1.14, then to 1.15? 

The "stream missing" warnings do not come from BentoBox in any way. 

To me this looks like an unsuccessful world conversion (direct 1.12 to 1.15 world conversion is considered as a bad habit according to various posts on SpigotMC) which causes the chunks to somehow become unreadable by Paper. 

Ultimately, I think it might be related to Paper. Since it is your server software, BentoBox takes advantage of their asynchronous IO chunk operations. But if Paper can't read the chunk contents (since the stream is missing), then Watchdog kicks in and drops the task. And your server crashes. 

I'd recommend you to retry upgrading your world in a steadier fashion, step by step, in order to make sure this issue is not caused by that. Based on your statements, we currently have no means to get that hypothesis out of the picture.

**Comment by tastybento** [comment]
Also, they the latest 1.10.0 SNAPSHOT because that has better handling for converted worlds.

**Comment by vojta478** [comment]
I have tried upgrading the server progressively and it removed the "stream missing" errors, I will now try to run 1.10.0 snapshot and post the results here.

**Comment by tastybento** [comment]
If you have a lot of unowned islands then you may need to do `/island` a few times at the very beginning so BentoBox can learn where they are.

**Comment by vojta478** [comment]
Looks like upgrading to the snapshot 1.10.0 fixes the problem for me. Thanks for your great support.
