### ISSUE TITLE
nether and nether island reset

### ISSUE THREAD

**Issue by bckd00r** [BentoBoxWorld/BSkyBlock#402]
WHY CANNOT PLAYERS RESET THE NETHER AND END ISLANDS SEPARATELY?

I made this request months ago and they told me it would be added. but it doesn't seem to be added ..

The feature I want to add is very simple, only the player should be able to reset the [normal-nether-end] islands separately.

The "/island restart" command should only be applied to the specified name and should only work for that name.

Example: /island restart nether-end-normal

permissions and placeholder support must be added.

please don't ignore my messages, this feature can get a lot of noise!

**Comment by BONNe** [comment]
Well, the reason is simple:
In all dimensions, islands have the same coordinate. It would mean, that if the player resets his nether island, it would require regenerating all chunks in his nether island area, and paste a new nether blueprint. As it cannot be done instantly, due logic of the Minecraft server, it would take time. 
If you are suggesting to unlink dimension coordinates, so in each dimension islands could be with different coordinates... well, it would really mess up everything and would require a lot of work to rework how plugin, and some of addons works.

Also, you need to understand, BentoBox is free for use, so it is not the main income source for authors. They need to work, so they could earn money... This is a passion project and as tasty wrote: "It’s a labor of love!". It is developed in free time.
If you want instant feature implementation, probably you need to choose some premium plugin.

And about your request:
There is a way implemented how to reset just one dimension, however, not by user... at least not without using Minecraft bugs.

There is a feature: create-missing-nether-end-islands in the config. If the bedrock block is removed in the nether or end world, then it will regenerate the default nether/end island blueprint in that spot.
(it is not what you requested, but it is the only function currently exit)

**Comment by tastybento** [comment]
This isn't going to be done.
