### ISSUE TITLE
players cant eat and can't place saplings in certain areas

### ISSUE THREAD

**Issue by Eonnnn** [BentoBoxWorld/BSkyBlock#43]
Perhaps I am missing a permission?

**Comment by tastybento** [comment]
Err no. Sounds like a bug. What is your setup?

**Comment by Eonnnn** [comment]
What do you mean?
I'm using Spigot 1.13.2 Multiverse
WorldGuard is active in that world, i've disabled it and no results
BSkyblock 1.0

**Comment by tastybento** [comment]
When you fill out a bug report, there's a request for a number of things to help debug the issue (see below). The key info I'd like to know is what other plugins are you using? Do you have Essentials AntiBuild or something similar? There's no blocking of hunger or sapling planting built into BSkyBlock so I'm guessing it's probably another plugin. 

**Description**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior:**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): []
 - OS: [e.g. iOS]
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**
Add any other context about the problem here.

**Comment by tastybento** [comment]
I'd like to understand why this happens...
