### ISSUE TITLE
Customizable settings menu and customizable island schematics and items in chest (and animal)

### ISSUE THREAD

**Issue by LikeABoss9** [BentoBoxWorld/BSkyBlock#58]
Hi! 

1) I just wanted to change items in the chest and island schematic (something like menu where user can choice the island schematic depending on the permisions he have [VIP island, Super VIP island e.t.c.] ).

2) And I wanted to change items in chest for diffrent players also depending on permisions he have or depending on island schematic which he chose.

3) I would like to be able to turn off the cow on island also depending on permisions player have or depending on island schematic which he chose.

Sorry for my English :(

**Comment by tastybento** [comment]
You have to create new schems to do that because it's not done via config settings.

Use the admin schem command to build and save new schems.

Then players can use the /island create (name) or /is reset (name) to use them (if they have the correct permission, i.e., bskyblock.island.create.name-of-schem)
