### ISSUE TITLE
Support for spawn world set as BSkyblock world | Maybe ore generator?

### ISSUE THREAD

**Issue by LukeZurg22** [BentoBoxWorld/BSkyBlock#83]
There should be support to set the main initial spawn world as a skyblock world. There is /bsbadmin setspawn to set spawn on an island, so that could could as a spawn location even with other plugins like CMI or multiverse spawn-setting function with no problem.

The problem that island ownership is also reset with prior settings set to default and the owner of the spawn island being untrusted.

Shouldn't be too much for an ore generator in there too but if not, its understandable.

**Comment by LukeZurg22** [comment]
Support for an already existing bskyblock would should also be fine, even if it means removing preexisting flatworld chunks although the setting that DOES that should work right in that regard.

**Comment by BONNe** [comment]
Please, do not put multiple feature requests in single request. It is hard to manage them afterwards. 

BSkyblock cannot do both of your requested things.

1. World management is controlled by BentoBox. So any requests about managing worlds should be done in BentoBox git.

2. Ore generator is planed... but currently noone has started to work on it.

**Comment by Poslovitch** [comment]
As BONNe already stated:

1. It's handled by BentoBox. However, as we're not loading at STARTUP (due to how addons work and need to hook into plugins), we cannot set the default world to be one of our gamemodes' world. That's a Bukkit limitation (or maybe even a NMS limitation) we cannot do anything about.
2. We're waiting for someone to start working on the ore gen addon. For the meantime, there is a great alternative plugin created by one of our contributors: https://www.spigotmc.org/resources/customoregen.9532/

Closing.
