### ISSUE TITLE
Island Size

### ISSUE THREAD

**Issue by Gecolay** [BentoBoxWorld/BSkyBlock#86]
**Question**

I have a short Question about the Size of Islands:

How can I create an Island with the Size of 199 x 199 where the Bedrock is the middle Block?
And how do I set it so that between the islands the non-build-area is only 1 block distance?
I just get it set that there is 2 or no block between the islands.

**Server Information:**

 - Java Version: Java 8
 - BentoBox version: 1.2.1
 - Addons installed? Skyblock 1.3.0 - SNAPSHOT

**Comment by tastybento** [comment]
Island distance has to be a factor of 16 because it must be a chunk boundary. So you'll need to play with either 192 or 208 as your island distance and adjust the protection range accordingly.

**Comment by Gecolay** [comment]
> Island distance has to be a factor of 16 because it must be a chunk boundary. So you'll need to play with either 192 or 208 as your island distance and adjust the protection range accordingly.

Is there no way to set a odd Value so you can have 1 Middle Block (the Bedrock).
It's very irritating when you have a odd Value of Blocks in one Direction and to the other there is a even Value.

Can you please add a Feature to set odd Values?
I liked the system of diameters from ASkyblock more.

**Comment by BONNe** [comment]
No. Cuz...
1. BentoBox feature that it ends all islands on chunk border it better for performance and it allows to maximize things like slime chunks and other chunk based systems.
2. Because of the (1) and how Minecraft coordinate system works, it is not possible to get both dimensions in an odd or even number.

To get what you want, BentoBox will need to redesign its Grid System calculation and remove chunk based system, that is easy to manage and calculate, just to get you odd numbers in both directions.
