### ISSUE TITLE
End island

### ISSUE THREAD

**Issue by silvasky54** [BentoBoxWorld/BSkyBlock#97]
Not a problem or suggestion. Just want some clarification on something.

When you go to the end and kill the ender dragon it spawns one of those 1 block portals. Going through it takes you to a different island outside my island range. Who, if anyone, owns this island and will it interfere with island creation, of other players, in the future?

**Screenshots**
![image](https://user-images.githubusercontent.com/25890347/54477835-7fef4600-4803-11e9-9763-e2c8fde5f301.png)

![image](https://user-images.githubusercontent.com/25890347/54477846-a4e3b900-4803-11e9-938d-28985386ff16.png)

**Server Information:**

[Please complete the following information:]
 - Database being used : Flat File
 - Java Version: Java 8
 - BentoBox version: 1.3.1
 - Addons installed? bskyblock 1.1, level 0.2, welcomewarps 0.1, challenges 0.5.1, greenhouses 0.0.2.
 - Other plugins? CMI, MV

**Comment by tastybento** [comment]
Killing the end dragon in BSkyBlock is not really defined. The default is that the dragon should not spawn at all. One reason is because of what you found out - when you kill the dragon a 1-portal block portal is made in a random location. So it could take you anywhere and also interfere with the end island of a player who already has an island there.

**Comment by silvasky54** [comment]
I see. Thanks for clearing that up. I'll leave it disabled for the time being then
